//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFabric.Assertive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetFabric.Assertive.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual is not &apos;null&apos; or empty..
        /// </summary>
        internal static string BeNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("BeNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual is not &apos;null&apos;, empty or whitespace..
        /// </summary>
        internal static string BeNullOrWhitespaceMessage {
            get {
                return ResourceManager.GetString("BeNullOrWhitespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual is &apos;null&apos; or empty..
        /// </summary>
        internal static string NotBeNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("NotBeNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual is &apos;null&apos;, empty or whitespace..
        /// </summary>
        internal static string NotBeNullOrWhitespaceMessage {
            get {
                return ResourceManager.GetString("NotBeNullOrWhitespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return by reference is not supported on target platforms previous to &apos;netstandard2.1&apos;. For the current target platform, set the &apos;testRefReturns&apos; parameter to &apos;false&apos; and use other method of comparison..
        /// </summary>
        internal static string RefReturnsMessage {
            get {
                return ResourceManager.GetString("RefReturnsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerators declared as &apos;ref struct&apos; are not supported. Set the &apos;testRefStructs&apos; parameter to &apos;false&apos; and use other method of comparison..
        /// </summary>
        internal static string RefStructMessage {
            get {
                return ResourceManager.GetString("RefStructMessage", resourceCulture);
            }
        }
    }
}
